# Run Dockerfile
services:
  gamepanel:
    image: gamepanel:dev
    build: .
    ports:
      - "4400:80"
    volumes:
      - ./:/var/www/html
      - ./_cfg/gamepanel/logs:/var/log/apache2
  
  panel_database:
    image: mysql:8
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 8e9f0e8f20ac30587d22d2113590e83c6010c215aceeefc94e3db55ba447fec968998767d57c45d968bfce36b03bfd1ff4cfbf60e9986e63dd6e3ee73801d982
      MYSQL_DATABASE: gamepanel
      MYSQL_USER: gamepanel
      MYSQL_PASSWORD: gamepanel
    volumes:
      - ./_cfg/panel_mysql:/var/lib/mysql
    
  game_database:
    image: mysql:8
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: gamedb
      MYSQL_USER: gamedb
      MYSQL_PASSWORD: gamedb
    volumes:
      - ./_cfg/game_mysql:/var/lib/mysql

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    environment:
      ADMINER_DESIGN: 'hydra'
      ADMINER_DEFAULT_SERVER: 'panel_database'

  cache:
    image: redis
    volumes:
      - ./_cfg/redis-data:/data
    command: redis-server --appendonly yes